name: Semgrep Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Run Semgrep scan
      uses: semgrep/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/owasp-top-ten
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      continue-on-error: true
      
    - name: Run Semgrep CLI and save JSON
      run: |
        # Install Semgrep CLI
        python3 -m pip install semgrep
        
        # Create reports directory if it doesn't exist
        mkdir -p security-reports
        
        # Run Semgrep scan and save to JSON file
        semgrep scan --config auto --json --json-output=security-reports/semgrep-results-$(date +%Y%m%d-%H%M%S).json
        
        # Also create a latest symlink for easy access
        cp security-reports/semgrep-results-*.json security-reports/semgrep-latest.json
        
    - name: Commit scan results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add security-reports/
        
        # Only commit if there are changes
        if ! git diff --staged --quiet; then
          git commit -m "Update Semgrep scan results [skip ci]"
          git push
        else
          echo "No changes to commit"
        fi
      continue-on-error: true
