name: OpenGrep Offline Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  opengrep:
    name: Offline OpenGrep Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y rsync
        python3 --version
        python3 -m pip install opengrep-cli

    - name: Setup SSH and Download Custom Rules
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 34.60.224.76 >> ~/.ssh/known_hosts

        rsync -avz -e "ssh -i ~/.ssh/id_rsa" \
          pranavanil123@34.27.77.137:/home/pranavanil123/Semgrep-rules ./custom-opengrep-rules

    - name: Run OpenGrep with Custom Rules
      id: run_scan
      run: |
        mkdir -p security-reports
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        opengrep scan --config ./custom-opengrep-rules --path . \
          --exclude custom-opengrep-rules \
          --exclude .github \
          --json > security-reports/opengrep-results-${TIMESTAMP}.json

        echo "file_name=opengrep-results-${TIMESTAMP}.json" >> $GITHUB_OUTPUT

    - name: Convert OpenGrep JSON to CSV
      run: |
        python3 .github/scripts/semgrep_json_to_readable_csv.py \
          security-reports/${{ steps.run_scan.outputs.file_name }} \
          security-reports/results.csv

    - name: Upload CSV to remote VM
      run: |
        scp -i ~/.ssh/id_rsa security-reports/results.csv \
          pranavanil123@34.27.77.137:/home/pranavanil123/semgrep_findings/
