name: Semgrep Offline Security Scan with OpenAI Enrichment

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  semgrep:
    name: Offline Semgrep Scan + OpenAI Enrichment
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync python3-pip
          python3 -m pip install semgrep openai

      - name: Run Semgrep with Custom Rules (code-only)
        id: run_scan
        run: |
          mkdir -p security-reports
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)

          semgrep scan --config=auto \
            --exclude=custom-semgrep-rules \
            --exclude=.github \
            --json --json-output=security-reports/semgrep-results-${TIMESTAMP}.json

          echo "file_name=semgrep-results-${TIMESTAMP}.json" >> $GITHUB_OUTPUT

      - name: Enrich Semgrep Results with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FILE_NAME: ${{ steps.run_scan.outputs.file_name }}
        run: |
          cat > enrich_with_openai.py << 'EOF'
          import os
          import json
          import time
          from openai import OpenAI, APIError

          client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
          file_name = "security-reports/" + os.getenv("FILE_NAME")

          with open(file_name, "r") as f:
              findings = json.load(f)

          prompt = f"""
          You are a security code reviewer AI.
          Given the following Semgrep findings as JSON:
          {json.dumps(findings)}
          For each finding, add a new field "ai_fix" with a concise, actionable fix suggestion.
          Return ONLY valid JSON.
          """

          enriched_text = None
          for attempt in range(3):
              try:
                  response = client.chat.completions.create(
                      model="gpt-4o-mini",
                      messages=[{"role": "user", "content": prompt}],
                      temperature=0.2,
                      max_tokens=8192,
                  )
                  enriched_text = response.choices[0].message.content
                  break
              except APIError as e:
                  print(f"[OpenAI] API error: {e}, retrying in {2**attempt} seconds...")
                  if "insufficient_quota" in str(e).lower():
                      print("[OpenAI] Insufficient quota detected, stopping retries.")
                      break
                  time.sleep(2 ** attempt)

          if enriched_text is None:
              print("[OpenAI] API unavailable, using original findings.")
              enriched = findings
          else:
              try:
                  enriched = json.loads(enriched_text)
              except json.JSONDecodeError:
                  print("[OpenAI] Returned invalid JSON, using original findings.")
                  enriched = findings

          enriched_file = "security-reports/enriched-" + os.getenv("FILE_NAME")
          with open(enriched_file, "w") as f:
              json.dump(enriched, f, indent=2)

          print(f"Enriched file saved as {enriched_file}")
          EOF

          python3 enrich_with_openai.py

      - name: Upload Raw and Enriched Results to VM
        run: |
          RAW_FILE=${{ steps.run_scan.outputs.file_name }}
          ENRICHED_FILE=enriched-${{ steps.run_scan.outputs.file_name }}

          scp -i ~/.ssh/id_rsa security-reports/$RAW_FILE \
            pranavanil123@34.59.19.208:/home/pranavanil123/findings/semgrep/

          scp -i ~/.ssh/id_rsa security-reports/$ENRICHED_FILE \
            pranavanil123@34.59.19.208:/home/pranavanil123/findings/semgrep/

      - name: Send Enriched Results to API
        run: |
          ENRICHED_FILE=enriched-${{ steps.run_scan.outputs.file_name }}
          curl -X POST https://391eb398-1c11-4d32-ab6f-92fd6dc89fe1-00-2ua28acjof5z6.kirk.replit.dev/api/upload/Sample-Project/sast \
            -H "Content-Type: application/json" \
            -d @security-reports/$ENRICHED_FILE
