name: Trivy Security Scan + SBOM Enrichment

on:
  workflow_run:
    workflows: ["Semgrep Offline Security Scan"]
    types:
      - completed

permissions:
  contents: read

jobs:
  trivy:
    name: Trivy SCA and Enriched SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- Install Trivy ----------
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl jq
          TRIVY_VERSION=0.65.0
          wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.deb
          sudo dpkg -i trivy_${TRIVY_VERSION}_Linux-64bit.deb

      # ---------- Install Parlay ----------
      - name: Install Parlay
        run: |
          PARLAY_VERSION=0.9.0
          wget https://github.com/snyk/parlay/releases/download/v${PARLAY_VERSION}/parlay_${PARLAY_VERSION}_linux_amd64.deb
          sudo dpkg -i parlay_${PARLAY_VERSION}_linux_amd64.deb
          parlay --help

      # ---------- Setup SSH ----------
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.57.235.175 >> ~/.ssh/known_hosts

      # ---------- Run Trivy SCA ----------
      - name: Run Trivy SCA (Filesystem Scan)
        id: sca
        run: |
          mkdir -p security-reports
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          trivy fs --security-checks vuln,secret,config \
            --format json \
            --output security-reports/trivy-sca-${TIMESTAMP}.json .
          echo "sca_file=trivy-sca-${TIMESTAMP}.json" >> $GITHUB_OUTPUT

      - name: Upload Trivy SCA to VM
        run: |
          scp -i ~/.ssh/id_rsa security-reports/${{ steps.sca.outputs.sca_file }} \
            pranavanil123@34.57.235.175:/home/pranavanil123/findings/trivy_sca/
          curl -X POST https://0813f8a6-e661-4de1-9c7e-dfb9cf5966f6-00-z1kfamu9ai30.pike.replit.dev/api/upload/ci-cd-test/sca -H "Content-Type: application/json" -d @security-reports/${{ steps.sca.outputs.sca_file }}

      # ---------- Run Trivy SBOM ----------
      - name: Run Trivy SBOM (SPDX-JSON)
        id: sbom
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          trivy fs --format spdx-json \
            --output security-reports/trivy-sbom-${TIMESTAMP}.json .
          echo "sbom_file=trivy-sbom-${TIMESTAMP}.json" >> $GITHUB_OUTPUT

      # ---------- Enrich SBOM with Parlay ----------
      - name: Enrich SBOM with Parlay
        id: enrich
        run: |
          INPUT=security-reports/${{ steps.sbom.outputs.sbom_file }}
          OUTPUT=security-reports/enriched-${{ steps.sbom.outputs.sbom_file }}
          parlay ecosystems enrich "$INPUT" | parlay scorecard enrich - > "$OUTPUT"
          echo "enriched_file=$(basename $OUTPUT)" >> $GITHUB_OUTPUT

      - name: Upload Enriched SBOM to VM
        run: |
          scp -i ~/.ssh/id_rsa security-reports/${{ steps.enrich.outputs.enriched_file }} \
            pranavanil123@34.57.235.175:/home/pranavanil123/findings/trivy_SBOM/
          curl -X POST https://0813f8a6-e661-4de1-9c7e-dfb9cf5966f6-00-z1kfamu9ai30.pike.replit.dev/api/upload/ci-cd-test/sbom -H "Content-Type: application/json" -d @security-reports/enriched-${{ steps.sbom.outputs.sbom_file }}
