name: Trivy Security Scan

on:
  workflow_run:
    workflows: ["Semgrep Offline Security Scan"]
    types:
      - completed

permissions:
  contents: read

jobs:
  trivy:
    name: Run Trivy SCA and SBOM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy (Pinned Version)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl jq
          TRIVY_VERSION=0.65.0
          wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.deb
          sudo dpkg -i trivy_${TRIVY_VERSION}_Linux-64bit.deb

      - name: Install Parlay (Pinned Version)
        run: |
          PARLAY_VERSION=0.1.4
          wget https://github.com/snyk/parlay/releases/download/v${PARLAY_VERSION}/parlay_${PARLAY_VERSION}_linux_amd64.tar.gz
          tar -xzf parlay_${PARLAY_VERSION}_linux_amd64.tar.gz
          sudo mv parlay /usr/local/bin/parlay
          parlay version

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.59.19.208 >> ~/.ssh/known_hosts

      # ------------ Trivy SCA ------------
      - name: Run Trivy SCA (Filesystem Scan)
        id: sca
        run: |
          mkdir -p security-reports
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          trivy fs --security-checks vuln,secret,config \
            --format json \
            --output security-reports/trivy-sca-${TIMESTAMP}.json .
          echo "sca_file=trivy-sca-${TIMESTAMP}.json" >> $GITHUB_OUTPUT

      - name: Upload Trivy SCA Result to VM
        run: |
          FILE_NAME=${{ steps.sca.outputs.sca_file }}
          scp -i ~/.ssh/id_rsa security-reports/$FILE_NAME \
            pranavanil123@34.59.19.208:/home/pranavanil123/findings/trivy_sca/

      # ------------ Trivy SBOM ------------
      - name: Run Trivy SBOM (spdx-json)
        id: sbom
        run: |
          mkdir -p security-reports
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          trivy fs --format spdx-json \
            --output security-reports/trivy-sbom-${TIMESTAMP}.json .
          echo "sbom_file=trivy-sbom-${TIMESTAMP}.json" >> $GITHUB_OUTPUT

      - name: Enrich SBOM with Parlay
        id: enrich
        run: |
          INPUT_FILE=security-reports/${{ steps.sbom.outputs.sbom_file }}
          OUTPUT_FILE=security-reports/enriched-${{ steps.sbom.outputs.sbom_file }}
          parlay ecosystems enrich $INPUT_FILE | parlay snyk enrich - > $OUTPUT_FILE
          echo "enriched_file=$(basename $OUTPUT_FILE)" >> $GITHUB_OUTPUT

      - name: Upload Enriched SBOM to VM
        run: |
          FILE_NAME=${{ steps.enrich.outputs.enriched_file }}
          scp -i ~/.ssh/id_rsa security-reports/$FILE_NAME \
            pranavanil123@34.59.19.208:/home/pranavanil123/findings/trivy_SBOM/
