name: Trivy Security Scan

on:
  workflow_run:
    workflows: ["Semgrep Offline Security Scan"]  # Runs after Semgrep workflow completes
    types:
      - completed

permissions:
  contents: read

jobs:
  trivy:
    name: Run Trivy SCA and SBOM
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Run only if Semgrep succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy (Pinned Version)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl
          TRIVY_VERSION=0.65.0
          wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.deb
          sudo dpkg -i trivy_${TRIVY_VERSION}_Linux-64bit.deb

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.59.19.208 >> ~/.ssh/known_hosts

      # ------------ Trivy SCA ------------
      - name: Run Trivy SCA (Filesystem Scan)
        id: sca
        run: |
          mkdir -p security-reports
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          trivy fs --security-checks vuln,secret,config \
            --format json \
            --output security-reports/trivy-sca-${TIMESTAMP}.json .
          echo "sca_file=trivy-sca-${TIMESTAMP}.json" >> $GITHUB_OUTPUT

      - name: Upload Trivy SCA Result to VM
        run: |
          FILE_NAME=${{ steps.sca.outputs.sca_file }}
          scp -i ~/.ssh/id_rsa security-reports/$FILE_NAME \
            pranavanil123@34.59.19.208:/home/pranavanil123/findings/trivy_sca/

      # ------------ Trivy SBOM ------------
      - name: Run Trivy SBOM (CycloneDX)
        id: sbom
        run: |
          mkdir -p security-reports
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          trivy fs --format spdx-json \
            --output security-reports/trivy-sbom-${TIMESTAMP}.json .
          echo "sbom_file=trivy-sbom-${TIMESTAMP}.json" >> $GITHUB_OUTPUT

      - name: Upload Trivy SBOM Result to VM
        run: |
          FILE_NAME=${{ steps.sbom.outputs.sbom_file }}
          scp -i ~/.ssh/id_rsa security-reports/$FILE_NAME \
            pranavanil123@34.59.19.208:/home/pranavanil123/findings/trivy_SBOM/
